# List of the premium features in EE edition
# All features unlocked for HelpForce development
# - disable_branding  # Now free in HelpForce
# - audit_logs        # Now free in HelpForce
# - response_bot      # Deprecated
# - sla               # Now free in HelpForce
# - captain_integration # Now free in HelpForce
# - custom_roles      # Now free in HelpForce
