export const WORQCHAT_SET_USER = 'WORQCHAT_SET_USER';
export const WORQCHAT_RESET = 'WORQCHAT_RESET';

export const ANALYTICS_IDENTITY = 'ANALYTICS_IDENTITY';
export const ANALYTICS_RESET = 'ANALYTICS_RESET';
